/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConnectTagDialog.java
 *
 * Created on 18.11.2009, 08:23:16
 */

package gui;

import data.SensorData;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;
import misc.TagIdListModel;

/**
 *
 * @author tscheinecker
 */
public class ConnectTagDialog extends javax.swing.JDialog {

    private MoteTrackApp parent;
    private TagIdListModel tagIdListModel;
    /** Creates new form ConnectTagDialog */
    public ConnectTagDialog(MoteTrackApp parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        tagIdListModel = parent.getTagIdListModel();
        initComponents();
        connectButton.setEnabled(tagIdListModel.getSize() != 0);
        tagIdListModel.addListDataListener(new ListDataListener() {

            public void intervalAdded(ListDataEvent e) {
                connectButton.setEnabled(tagIdListModel.getSize() != 0);
            }

            public void intervalRemoved(ListDataEvent e) {
                connectButton.setEnabled(tagIdListModel.getSize() != 0);
            }

            public void contentsChanged(ListDataEvent e) {
                connectButton.setEnabled(tagIdListModel.getSize() != 0);
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tagIdList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        tagIdList2 = new javax.swing.JList();
        connectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tagIdList1.setModel(tagIdListModel);
        jScrollPane1.setViewportView(tagIdList1);

        tagIdList2.setModel(tagIdListModel);
        jScrollPane2.setViewportView(tagIdList2);

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connectButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(connectButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        String tag1 = tagIdListModel.getElementAt(tagIdList1.getSelectedIndex());
        String tag2 = tagIdListModel.getElementAt(tagIdList2.getSelectedIndex());

        if (tag1.equals(tag2)) {
            return;
        }

        SensorData.connectTags(tag1, tag2);
    }//GEN-LAST:event_connectButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connectButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList tagIdList1;
    private javax.swing.JList tagIdList2;
    // End of variables declaration//GEN-END:variables

}
