/*
 * SimpleGLCanvas.java
 *
 * Created on 30. Juli 2008, 16:18
 */

package gui;

import exceptions.IllegalTagIdFormatException;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import javax.swing.JSpinner;
import javax.swing.KeyStroke;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.ListSelectionEvent;
import com.sun.opengl.util.Animator;
import data.HistoryCollector;
import data.SensorData;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.media.opengl.GLCanvas;
import javax.media.opengl.GLCapabilities;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.UIManager;
import javax.swing.WindowConstants;
import javax.swing.event.ListSelectionListener;
import misc.TagIdListModel;
import network.ServerDataReader;
import network.client.ReplayServerClient;

/**
 *
 * @author cylab
 * @author mbien
 */
public class MoteTrackApp extends JFrame {

    static {
        // When using a GLCanvas, we have to set the Popup-Menues to be HeavyWeight,
        // so they display properly on top of the GLCanvas
        JPopupMenu.setDefaultLightWeightPopupEnabled(false);
    }
    
    private Animator animator;
    private DataVisualisation renderer;
    private ServerDataReader client;
    private HistoryCollector historyCollector;
    private StartReplayServerDialog startServerDialog;
    private ConnectToServerDialog connectToServerDialog;

    private void autoStartReplayServer() {
        startServerDialog.startServer();
    }

    /** Creates new form MainFrame */
    public MoteTrackApp() {

        startServerDialog = new StartReplayServerDialog(this, true);
        connectToServerDialog = new ConnectToServerDialog(this, true);

        // for debugging only
       // autoStartReplayServer();

        initComponents();

        tagIdList.addListSelectionListener(listSelectionListener);

        setTitle("Motion Tracking Application");

        renderer = new DataVisualisation();
        canvas.addGLEventListener(renderer);
        animator = new Animator(canvas);

        // This is a workaround for the GLCanvas not adjusting its size, when the frame is resized.
        canvas.setMinimumSize(new Dimension());         
        
        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                // Run this on another thread than the AWT event queue to
                // make sure the call to Animator.stop() completes before
                // exiting
                new Thread(new Runnable() {

                    public void run() {
                        animator.stop();
                        System.exit(0);
                    }
                }).start();
            }
        });
    }

    @Override
    public void setVisible(boolean show){
        if(!show)
            animator.stop();
        super.setVisible(show);
        if(show)
            animator.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        JLabel tagIdListLabel = new JLabel();
        canvas = new GLCanvas(createGLCapabilites());
        historyCheckBox = new JCheckBox();
        beacon2dCheckBox = new JCheckBox();
        resetButton = new JButton();
        tagIdListScrollPane = new JScrollPane();
        tagIdList = new JList();
        planeCheckBox = new JCheckBox();
        tagSizeSpinner = new JSpinner();
        tagSizeLabel = new JLabel();
        jMenuBar1 = new JMenuBar();
        fileMenu = new JMenu();
        startReplayServerItem = new JMenuItem();
        connectMenuItem = new JMenuItem();
        connectTagsMenuItem = new JMenuItem();
        exitMenuItem = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        tagIdListLabel.setText("List of Tag IDs");

        historyCheckBox.setSelected(true);
        historyCheckBox.setText("draw history");
        historyCheckBox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                historyCheckBoxActionPerformed(evt);
            }
        });

        beacon2dCheckBox.setSelected(true);
        beacon2dCheckBox.setText("draw 2D beacon");
        beacon2dCheckBox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                beacon2dCheckBoxActionPerformed(evt);
            }
        });

        resetButton.setText("Reset View");
        resetButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        tagIdList.setModel(new TagIdListModel());
        tagIdListScrollPane.setViewportView(tagIdList);

        planeCheckBox.setText("show Plane");
        planeCheckBox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                planeCheckBoxActionPerformed(evt);
            }
        });

        tagSizeSpinner.setValue(new Integer(2));
        tagSizeSpinner.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                tagSizeSpinnerStateChanged(evt);
            }
        });

        tagSizeLabel.setText("Tag drawing size (dm)");

        fileMenu.setText("File");

        startReplayServerItem.setText("Start Replay Server");
        startReplayServerItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                startReplayServerItemActionPerformed(evt);
            }
        });
        fileMenu.add(startReplayServerItem);

        connectMenuItem.setText("Connect to Server");
        connectMenuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                connectMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(connectMenuItem);

        connectTagsMenuItem.setText("Connect Tags");
        fileMenu.add(connectTagsMenuItem);

        exitMenuItem.setAction(exitAction);
        exitMenuItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_Q, InputEvent.CTRL_MASK));
        exitMenuItem.setText("Exit");
        fileMenu.add(exitMenuItem);

        jMenuBar1.add(fileMenu);

        setJMenuBar(jMenuBar1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(tagIdListLabel)
                    .addComponent(tagIdListScrollPane, GroupLayout.PREFERRED_SIZE, 146, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(canvas, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(historyCheckBox)
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addComponent(beacon2dCheckBox)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(planeCheckBox)
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addComponent(tagSizeSpinner, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(tagSizeLabel)
                        .addPreferredGap(ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(resetButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(tagIdListLabel)
                    .addComponent(historyCheckBox)
                    .addComponent(beacon2dCheckBox)
                    .addComponent(resetButton)
                    .addComponent(planeCheckBox)
                    .addComponent(tagSizeSpinner, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(tagSizeLabel))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(tagIdListScrollPane, GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addComponent(canvas, GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void historyCheckBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_historyCheckBoxActionPerformed
        renderer.setDrawHistory(historyCheckBox.isSelected());
    }//GEN-LAST:event_historyCheckBoxActionPerformed

    private void beacon2dCheckBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_beacon2dCheckBoxActionPerformed
        renderer.setDraw2dBeachon(beacon2dCheckBox.isSelected());
    }//GEN-LAST:event_beacon2dCheckBoxActionPerformed

    private void resetButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        renderer.reset();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void startReplayServerItemActionPerformed(ActionEvent evt) {//GEN-FIRST:event_startReplayServerItemActionPerformed
        startServerDialog.setLocationRelativeTo(this);
        startServerDialog.setVisible(true);
    }//GEN-LAST:event_startReplayServerItemActionPerformed

    private void connectMenuItemActionPerformed(ActionEvent evt) {//GEN-FIRST:event_connectMenuItemActionPerformed
        connectToServerDialog.setLocationRelativeTo(this);
        connectToServerDialog.setVisible(true);
    }//GEN-LAST:event_connectMenuItemActionPerformed

    private void planeCheckBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_planeCheckBoxActionPerformed
        renderer.setDrawPlane(planeCheckBox.isSelected());
    }//GEN-LAST:event_planeCheckBoxActionPerformed

    private void tagSizeSpinnerStateChanged(ChangeEvent evt) {//GEN-FIRST:event_tagSizeSpinnerStateChanged
        renderer.setTagSize(Double.parseDouble(tagSizeSpinner.getValue().toString())/10);
    }//GEN-LAST:event_tagSizeSpinnerStateChanged

    /**
     * Called from within initComponents().
     * hint: to customize the generated code choose 'Customize Code' in the contextmenu
     * of the selected UI Component you wish to cutomize in design mode.
     * @return Returns customized GLCapabilities.
     */
    private GLCapabilities createGLCapabilites() {
        
        GLCapabilities capabilities = new GLCapabilities();
        capabilities.setHardwareAccelerated(true);

        // try to enable 2x anti aliasing - should be supported on most hardware
        capabilities.setNumSamples(2);
        capabilities.setSampleBuffers(true);
        
        return capabilities;
    }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        // Run this in the AWT event thread to prevent deadlocks and race conditions
        EventQueue.invokeLater(new Runnable() {
            public void run() {

                // switch to system l&f for native font rendering etc.
                try{
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                }catch(Exception ex) {
                    Logger.getLogger(getClass().getName()).log(Level.INFO, "can not enable system look and feel", ex);
                }

                MoteTrackApp frame = new MoteTrackApp();

                frame.setVisible(true);
            }
        });
    }

    private Action exitAction = new AbstractAction("EXIT") {

        public void actionPerformed(ActionEvent e) {
            System.exit(0);
        }
    };

    private ListSelectionListener listSelectionListener = new ListSelectionListener() {

        public void valueChanged(ListSelectionEvent e) {
            Object[] selectedIds = tagIdList.getSelectedValues();
            ArrayList<String> selectedIdsList = new ArrayList<String>();
            for (Object id : selectedIds) {
                selectedIdsList.add((String)id);
            }
            try {
                selectedIdsList = SensorData.format(selectedIdsList, true);
            } catch (IllegalTagIdFormatException ex) {
                String msg = "IllegalTagIdFormatException occured while handling selection change event - ID: "+ex.getIllegalTagId();
                System.err.println(msg);
                Logger.getLogger(MoteTrackApp.class.getName()).log(Level.SEVERE, msg, ex);
            }

            renderer.setSelectedTagIds(selectedIdsList);
        }
    };

    public void connectToServer(ServerDataReader client, HistoryCollector historyCollector) {
        this.client = client;
        this.historyCollector = historyCollector;
        ((TagIdListModel) tagIdList.getModel()).setHistorycollector(historyCollector);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JCheckBox beacon2dCheckBox;
    private GLCanvas canvas;
    private JMenuItem connectMenuItem;
    private JMenuItem connectTagsMenuItem;
    private JMenuItem exitMenuItem;
    private JMenu fileMenu;
    private JCheckBox historyCheckBox;
    private JMenuBar jMenuBar1;
    private JCheckBox planeCheckBox;
    private JButton resetButton;
    private JMenuItem startReplayServerItem;
    private JList tagIdList;
    private JScrollPane tagIdListScrollPane;
    private JLabel tagSizeLabel;
    private JSpinner tagSizeSpinner;
    // End of variables declaration//GEN-END:variables

}
